# Generated by Django 2.1.10 on 2019-07-14 05:48

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('nnuh_doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='doctor_content', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='doctortranslation',
            name='sub_speciality',
            field=models.CharField(blank=True, max_length=255, verbose_name='sub speciality'),
        ),
    ]
