# Generated by Django 2.1.10 on 2019-07-27 13:20

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('nnuh_doctors', '0002_auto_20190714_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email Address')),
                ('birth_date', models.CharField(blank=True, max_length=255, verbose_name='Birth Date')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='content_bottom',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_content_bottom', slotname='doctor_content_bottom', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sidebar',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_sidebar', slotname='doctor_sidebar', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sidebar_bottom',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_sidebar_bottom', slotname='doctor_sidebar_bottom', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_content', slotname='doctor_content', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='nnuh_doctors.Doctor', verbose_name='Doctor'),
        ),
    ]
