# Generated by Django 2.1.10 on 2022-03-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnuh_doctors', '0004_auto_20190923_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='clinic_phone'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='clinic_time'),
        ),
    ]
