# Generated by Django 2.1.10 on 2022-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnuh_doctors', '0005_auto_20220310_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic_time',
        ),
        migrations.AddField(
            model_name='doctortranslation',
            name='clinic_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='clinic_time'),
        ),
    ]
