# Generated by Django 2.1.10 on 2022-04-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnuh_doctors', '0008_auto_20220323_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortranslation',
            name='clinic_hour',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='clinic_hour'),
        ),
    ]
