version: '2'

services:

  django:
    build:
      context: ./provision/django/
      dockerfile: Dockerfile
#    build: ./provision/django
    image: nnuh_django
    depends_on:
      - db
      - cache
      - search
    volumes:
      - ./src:/code:cached
      - ./public:/public:cached
    ports:
      - "8000:8000"

  db:
#    build:
#      context: ./provision/db/
#      dockerfile: Dockerfile
#    image: laws_portal_db
    image: mysql:5
    command: --max_allowed_packet=32505856 --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=nnuh
    volumes:
      - ./storage/db:/var/lib/mysql
      - ./provision/db/nnuh.sql:/tmp/nnuh.sql
    ports:
     - "3360:3306"

  cache:
    image: memcached:alpine
#    volumes:
#      - ./storage/cache/data:/data

  search:
    image: elasticsearch:5.6-alpine
    volumes:
      - ./storage/search/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  webpack:
    build:
      context: ./provision/webpack/
      dockerfile: Dockerfile
    image: nnuh_webpack
    depends_on:
      - django
    volumes:
      - ./src/conf/theme:/app/theme
      - ./src/conf/static:/app/static
    ports:
      - "3000:3000"

networks:
  default:
#    driver: overlay
    ipam:
#      driver: default
      config:
      -
        subnet: 192.168.181.0/24