# Generated by Django 2.0.13 on 2022-03-08 06:55

import aldryn_apphooks_config.fields
import aldryn_translation_tools.models
import app_data.fields
import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aldryn_people', '0018_auto_20160802_1852'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publishing date')),
                ('deadline_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='deadline date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active?')),
                ('can_apply', models.BooleanField(default=True, verbose_name='viewer can apply for the job?')),
                ('cv_option', models.BooleanField(default=True, verbose_name='CV file')),
                ('tawjihi_option', models.BooleanField(default=True, verbose_name='Tawjihi Certificate file')),
                ('certificate_option', models.BooleanField(default=False, verbose_name='BA University Certificate')),
                ('ID_option', models.BooleanField(default=True, verbose_name='Card ID option ')),
                ('personal_photo_option', models.BooleanField(default=False, verbose_name='Personal Photo File')),
                ('work_cert_option', models.BooleanField(default=True, verbose_name='Work Certificate File')),
                ('org_cert_option', models.BooleanField(default=True, verbose_name='Org Certificate File')),
                ('recommendation_letters_option', models.BooleanField(default=False, verbose_name='Recommendation Letters File')),
                ('personal_statment_option', models.BooleanField(default=False, verbose_name='Personal Statement File')),
                ('marks_list_option', models.BooleanField(default=False, verbose_name='Marks_List')),
                ('insurance_doc_option', models.BooleanField(default=False, verbose_name='Insurance Doc')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-publishing_date'],
            },
            bases=(aldryn_translation_tools.models.TranslationHelperMixin, aldryn_translation_tools.models.TranslatedAutoSlugifyMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JobsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('namespace', models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace')),
                ('app_data', app_data.fields.AppDataField(default='{}', editable=False)),
                ('paginate_by', models.PositiveIntegerField(default=5, help_text='When paginating list views, how many articles per page?', verbose_name='Paginate size')),
                ('pagination_pages_start', models.PositiveIntegerField(default=10, help_text='When paginating list views, after how many pages should we start grouping the page numbers.', verbose_name='Pagination pages start')),
                ('pagination_pages_visible', models.PositiveIntegerField(default=4, help_text='When grouping page numbers, this determines how many pages are visible on each side of the active page.', verbose_name='Pagination pages visible')),
                ('create_authors', models.BooleanField(default=True, help_text='Automatically create authors from logged-in user?', verbose_name='Auto-create authors?')),
                ('template_prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prefix for template dirs')),
            ],
            options={
                'verbose_name': 'NNUH Jobs configuration',
                'verbose_name_plural': 'NNUH Jobs configurations',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JobsConfigTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('app_title', models.CharField(max_length=234, verbose_name='name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='nnuh_jobs.JobsConfig')),
            ],
            options={
                'verbose_name': 'NNUH Jobs configuration Translation',
                'db_table': 'nnuh_jobs_jobsconfig_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='JobTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(default='', help_text="Provide this job's title.", max_length=500, verbose_name='title')),
                ('slug', models.SlugField(blank=True, help_text='Used in the URL. If changed, the URL will change. Clear it to have it re-created automatically.', max_length=255, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='nnuh_jobs.Job')),
            ],
            options={
                'verbose_name': 'Job Translation',
                'db_table': 'nnuh_jobs_job_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='job',
            name='app_config',
            field=aldryn_apphooks_config.fields.AppHookConfigField(help_text='When selecting a value, the form is reloaded to get the updated default', on_delete=django.db.models.deletion.CASCADE, to='nnuh_jobs.JobsConfig', verbose_name='NNUH Jobs Configuration'),
        ),
        migrations.AddField(
            model_name='job',
            name='apply_form',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_form', slotname='Job_Form', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='job',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aldryn_people.Person', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='job',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_content', slotname='Job_Description', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='job',
            name='featured_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='featured image'),
        ),
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterUniqueTogether(
            name='jobtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='jobsconfigtranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
