# Generated by Django 2.1.10 on 2022-02-07 08:15

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nnuh_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='jobpost',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='nnuh_jobs.Job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='certificate',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Job_Certificate', slotname='Job_Certificate', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Job_CV', slotname='Job_CV', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Job_Expeience', slotname='Job_Expeience', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='user',
            name='master_cert',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Job_Master', slotname='Job_Master', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tawjihi',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Job_Tawjihi', slotname='Job_Tawjihi', to='cms.Placeholder'),
        ),
    ]
