# Generated by Django 2.1.10 on 2022-02-14 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nnuh_jobs', '0002_auto_20220207_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='job',
            name='can_apply',
            field=models.BooleanField(default=True, verbose_name='viewer can apply for the job?'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active?'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Applier', to='nnuh_jobs.User'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='jobpost',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Job', to='nnuh_jobs.Job'),
        ),
        migrations.AlterField(
            model_name='usertranslation',
            name='relations',
            field=models.BooleanField(default=False, verbose_name='realtion'),
        ),
    ]
