# Generated by Django 2.1.10 on 2022-02-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('nnuh_jobs', '0003_auto_20220214_0935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Applier',
        ),
        migrations.RenameModel(
            old_name='UserTranslation',
            new_name='ApplierTranslation',
        ),
        migrations.AlterModelOptions(
            name='appliertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'applier Translation'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_published',
        ),
        migrations.AlterModelTable(
            name='appliertranslation',
            table='nnuh_jobs_applier_translation',
        ),
    ]
