# Generated by Django 2.1.10 on 2022-02-14 11:52

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('nnuh_jobs', '0004_auto_20220214_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='featured_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='featured image'),
        ),
    ]
