# Generated by Django 2.1.10 on 2022-03-30 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('google-plus', 'Google +'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('linkedin', 'Linkedin'), ('vk', 'VK'), ('buffer', 'Buffer'), ('email', 'Email')], default=None, max_length=20, null=True, verbose_name='button')),
                ('icononly', models.BooleanField(default=False, verbose_name='icon only')),
                ('text', models.CharField(blank=True, max_length=50, null=True, verbose_name='button label')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialShareKitPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_socialsharekit_socialsharekitplugin', serialize=False, to='cms.CMSPlugin')),
                ('size', models.CharField(choices=[('xs', 'Extra Small'), ('s', 'Small'), ('sm', 'Regular'), ('lg', 'Large')], default='sm', max_length=2, verbose_name='size')),
                ('style', models.CharField(choices=[('square', 'Square'), ('round', 'Round'), ('rounded', 'Rounded')], default='square', max_length=10, verbose_name='style')),
                ('count', models.BooleanField(default=False, verbose_name='count')),
                ('greyscale', models.BooleanField(default=False, verbose_name='greyscale')),
                ('group_width', models.CharField(blank=True, default='', help_text='Need used in conjunction with button *label*. Ex: 120px or 100%.', max_length=5, null=True, verbose_name='block width')),
                ('forceinit', models.BooleanField(default=False, help_text='In case if you want to initialize right away without waiting for DOM to load.', verbose_name='forceInit')),
                ('sticky', models.BooleanField(default=False, verbose_name='sticky')),
                ('center', models.BooleanField(default=False, verbose_name='center')),
                ('button_position', models.CharField(blank=True, choices=[('left', 'Left side'), ('right', 'Right side'), ('bottom', 'Bottom')], default=None, max_length=10, null=True, verbose_name='buttons position')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='socialbutton',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='cmsplugin_socialsharekit.SocialShareKitPlugin'),
        ),
    ]
